from models.asientos import Asientos
from models.autobuses import Autobuses
from models.boletos import Boletos
from models.choferes import Choferes
from models.estacion import Estacion
from models.paradas import Paradas
from models.pasajeros import Pasajeros
from models.status_boletos import StatusBoletos
from models.ubicaciones_sede import UbicacionesSede
from models.viajes import Viajes
from models.boletos_por_mes import BoletosPorMes
from models.historial_viajes import HistorialViajes
from models.analisis_viajes import AnalisisViajes
from models.pasajeros_por_viaje import PasajerosPorViaje
from models.asientos_ocupados import AsientosOcupados
from models.rutas_del_dia import RutasDelDia
from models.ingresos_por_mes import IngresosPorMes
from models.ocupacion_promedio import OcupacionPromedio
from models.pasajeros_por_autobus import PasajerosPorAutobus
from models.boletos_por_tipo_asiento import BoletosPorTipoAsiento
from models.choferes_por_autobus import ChoferesPorAutobus
